FROM --platform=linux/x86_64 nginx:latest

#health check
RUN apt-get update && apt-get install -y curl vim sudo lsof

# インクルード用のディレクトリ内を削除
RUN rm -f /etc/nginx/conf.d/*

ADD nginx.conf /etc/nginx/myapp.conf

# ビルド完了後にnginxを起動
CMD /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/myapp.conf

EXPOSE 80